# https://www.strongswan.org/testing/testresults/ikev2/rw-psk-fqdn/
# https://www.strongswan.org/testing/testresults/ikev2/rw-psk-fqdn/moon.strongswan.conf

swanctl {
  load = random openssl 
}

charon-systemd {
  load = random nonce openssl kernel-netlink socket-default updown vici
}
